### ISSUE TITLE
Customizing captcha image

### ISSUE THREAD

**Issue by morilog** [Gregwar/CaptchaBundle#160]
How can i add css classes to captcha image?

**Comment by platinumgroupmedia** [comment]
Yes, please on the next future release, at the minimum add a css class so it can be styled.

**Comment by Gregwar** [comment]
You mean on the `<img>` tag, right?
(https://github.com/Gregwar/CaptchaBundle/blob/master/Resources/views/captcha.html.twig#L6)

**Comment by platinumgroupmedia** [comment]
Yes please. For some reason every time I use the Captcha Bundle, it always needs 10px of margin-left because of the way our designer lays out our pages. I have manually gone in and modified the view in the bundle and added a class but when I deploy to production, composer will re-install your bundle and my class will be gone again. Thanks.

**Comment by Gregwar** [comment]
It's done, can you confirm it's OK?

**Comment by platinumgroupmedia** [comment]
<img class="captcha_image" id="{{ image_id }}" src="{{ captcha_code }}" alt="" title="captcha" width="{{ captcha_width }}" height="{{ captcha_height }}" />

It’s there. Thank you!

**Comment by Gregwar** [comment]
Thanks for reporting
